require('angshuman.options')
require('angshuman.keymaps')
require('angshuman.lazy')
require('angshuman.autocmds')
require('angshuman.lsp')
require('angshuman.debuggers')
require('angshuman.colorscheme')
